---
title: "Codebook"
author: "Clifton Bell"
date: "2023-05-23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Overview

The comma-delimited file entitled "Final_Means.csv" is a tidy data set that was created part of the course project for the Coursera class "Getting and Cleaning Data". The file contains the arithmetic mean values of various accelerometer data from a SamSamsung Galaxy S smartphone by subject and by activity. Final_Means.csv was created by applying the script run_analysis.R to the original accelerometer and gyrometer data.

##  Description of Original Data

The original data are available at:

https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip

A full description of the original data and associated project is available at:

http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones



## Variables

Following are the variables of the dataset entitled "Final_Means.csv"

1. **Subject**: The number corresponding to each of 30 volunteers within an age bracket of 19-48 years. 

2. **Activity_Name**: The name of each of six activities that the subjects performed while 
    wearing the SamSamsung Galaxy S smartphone.

Variables 3 - 68 correspond to the mean values (by subject and activity) of either the mean or standard deviation of various accelerometer or gyroscope measurements from the phones. The original variables are described in the README.txt files of the original authors as follows:

The features selected for this database come from the accelerometer and gyroscope 3-axial raw signals tAcc-XYZ and tGyro-XYZ. These time domain signals (prefix 't' to denote time) were captured at a constant rate of 50 Hz. Then they were filtered using a median filter and a 3rd order low pass Butterworth filter with a corner frequency of 20 Hz to remove noise. Similarly, the acceleration signal was then separated into body and gravity acceleration signals (tBodyAcc-XYZ and tGravityAcc-XYZ) using another low pass Butterworth filter with a corner frequency of 0.3 Hz. 

Subsequently, the body linear acceleration and angular velocity were derived in time to obtain Jerk signals (tBodyAccJerk-XYZ and tBodyGyroJerk-XYZ). Also the magnitude of these three-dimensional signals were calculated using the Euclidean norm (tBodyAccMag, tGravityAccMag, tBodyAccJerkMag, tBodyGyroMag, tBodyGyroJerkMag). 

Finally a Fast Fourier Transform (FFT) was applied to some of these signals producing fBodyAcc-XYZ, fBodyAccJerk-XYZ, fBodyGyro-XYZ, fBodyAccJerkMag, fBodyGyroMag, fBodyGyroJerkMag. (Note the 'f' to indicate frequency domain signals). 

These signals were used to estimate variables of the feature vector for each pattern:  
'-XYZ' is used to denote 3-axial signals in the X, Y and Z directions. 

## Clean-Up and Transformation

The course project required the student to create a single R script named run_analysis.R to accomplish five major steps. These steps are described below, along with a description of how the script accomplishes each step. 

STEP 1. Merge the training and the test sets to create one data set: The script uses fread() from the data.table package to read the training and test data and assign column names. It then combines the two datasets using rbind().  

STEP 2. Extract only the measurements on the mean and standard deviation for each measurement: The script uses select() from the dplyr package and the combine() helper to extract only the variables with mean() or std() in the variable name.

STEP 3. Uses descriptive activity names to name the activities in the data set: The script uses fread() to read in the training and test activity lists, and uses rbind() to combine them. It uses mutate() from the dplyr package to assign descriptive activity names. It then uses cbind() to combine the activity list with the accelerometer data.  

STEP 4. Appropriately labels the data set with descriptive variable names: The accelerometer data already had descriptive variable names from step 1. colnames() was used to rename the variables associated with activity number and activity name.

STEP 5. From the data set in step 4, creates a second, independent tidy data set with the average of each variable for each activity and each subject: This step required reading of the training and test subject list with fread(), combination of those datasets with rbind(), and cbind()ing of those data with the accelerometer data. The script uses group_by() to group the data by subject and activity, and then summarize_all() was used to calculate the desired means. write.csv() was used to write the resulting tidy dataset to a file called "Fina_Means.csv".

## Variables

Following are the variables of the dataset entitled "Final_Means.csv"

1. **Subject**: The number corresponding to each of 30 volunteers within an age bracket of 19-48 years. 

2. **Activity_Name**: The name of each of six activities that the subjects performed while 
    wearing the SamSamsung Galaxy S smartphone.

Variables 3 - 68 correspond to the mean values (by subject and activity) of either the mean or standard deviation of various accelerometer or gyroscope measurements from the phones, and are named as follows:

3. **tBodyAcc-mean()-X**
4. **tBodyAcc-mean()-Y**
5. **tBodyAcc-mean()-Z**          
6. **tGravityAcc-mean()-X**
7. **tGravityAcc-mean()-Y**
8. **tGravityAcc-mean()-Z**
9. **tBodyAccJerk-mean()-X**
10. **tBodyAccJerk-mean()-Y**
11. **tBodyAccJerk-mean()-Z**
12. **tBodyGyro-mean()-X**
13. **tBodyGyro-mean()-Y**
14. **tBodyGyro-mean()-Z**
15. **tBodyGyroJerk-mean()-X**  
16. **tBodyGyroJerk-mean()-Y**
17. **tBodyGyroJerk-mean()-Z**
18. **tBodyAccMag-mean()**
19. **tGravityAccMag-mean()**
20. **tBodyAccJerkMag-mean()**
21. **tBodyGyroMag-mean()**
22. **tBodyGyroJerkMag-mean()**
23. **fBodyAcc-mean()-X**
24. **fBodyAcc-mean()-Y**
25. **fBodyAcc-mean()-Z**          
26. **fBodyAccJerk-mean()-X**
27. **fBodyAccJerk-mean()-Y**
28. **fBodyAccJerk-mean()-Z**
29. **fBodyGyro-mean()-X**
30. **fBodyGyro-mean()-Y**   
31. **fBodyGyro-mean()-Z**
32. **fBodyAccMag-mean()**
33. **fBodyBodyAccJerkMag-mean()**
34. **fBodyBodyGyroMag-mean()**
35. **fBodyBodyGyroJerkMag-mean()**
36. **tBodyAcc-std()-X**
37. **tBodyAcc-std()-Y**
38. **tBodyAcc-std()-Z**
39. **tGravityAcc-std()-X**
40. **tGravityAcc-std()-Y**       
41. **tGravityAcc-std()-Z**
42. **tBodyAccJerk-std()-X**
43. **tBodyAccJerk-std()-Y**
44. **tBodyAccJerk-std()-Z**
45. **tBodyGyro-std()-X**        
46. **tBodyGyro-std()-Y**
47. **tBodyGyro-std()-Z**
48. **tBodyGyroJerk-std()-X**
49. **tBodyGyroJerk-std()-Y**
50. **tBodyGyroJerk-std()-Z**
51. **tBodyAccMag-std()**
52. **tGravityAccMag-std()**
53. **tBodyAccJerkMag-std()**
54. **tBodyGyroMag-std()**
55. **tBodyGyroJerkMag-std()**
56. **fBodyAcc-std()-X**
57. **fBodyAcc-std()-Y**
58. **fBodyAcc-std()-Z**
59. **fBodyAccJerk-std()-X**
60. **fBodyAccJerk-std()-Y**
61. **fBodyAccJerk-std()-Z**
62. **fBodyGyro-std()-X**
63. **fBodyGyro-std()-Y**
64. **fBodyGyro-std()-Z**
65. **fBodyAccMag-std()**
66. **fBodyBodyAccJerkMag-std()**
67. **fBodyBodyGyroMag-std()**
68. **fBodyBodyGyroJerkMag-std()** 